# This is a basic workflow to help you get started with Actions

name: Dockerfile Update

# Controls when the workflow will run
on:
  # 
  release:
    types: [published]

    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
      - name: Update Dockerfile
        run: |
          # Extract the current version from the Dockerfile
          FILE_VERSION=$(grep -oP 'ARG PYTORCH_IMG=\K\d{2}\.\d{2}' docker/Dockerfile.release)
          echo "Current file version: $FILE_VERSION"
          
          # Construct the date for the new version
          DATE=$(date '+%y.%m')
          echo "Current date: $DATE"
          
          # Separate new 
          YEAR=$(echo $DATE | cut -d'.' -f1)
          MONTH=$(echo $DATE | cut -d'.' -f2)
          
          ## --- Handling of special cases ---
          # Move to the previous year
          if [ "$MONTH" == "01" ]; then
          PREV_MONTH="12"
          YEAR=$(($YEAR - 1))
          # 09 and 08 will be interpreted in Octal, so they have to be handled differently 
          elif [ "$MONTH" == "09" ]; then
          PREV_MONTH="08"
          elif [ "$MONTH" == "08" ]; then
          PREV_MONTH="07"
          else
          PREV_MONTH=$(($MONTH - 1))
          # Ensure the previous month is 2 digits
          PREV_MONTH=$(printf "%02d" $PREV_MONTH)
          fi
          
          # Construct the new version
          NEW_VERSION="${YEAR}.${PREV_MONTH}"
          echo "Date for : $NEW_VERSION"
          ls
          cd docker
          ls
          
          # OLD_VERSION=${{ steps.get_version.outputs.old_version }}
          # NEW_VERSION=${{ steps.get_version.outputs.new_version }}
          sed -i.bak "s/$FILE_VERSION/$NEW_VERSION/g" Dockerfile.release
          touch test_file