# This is a basic workflow to help you get started with Actions

name: Dockerfile Update

# Controls when the workflow will run
on:
  # 
  release:
    types: [published]

    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Dockerfile
        run: |
          # Extract the current version from the Dockerfile
          FILE_VERSION=$(grep -oP 'ARG PYTORCH_IMG=\K\d{2}\.\d{2}' docker/Dockerfile.release)
          
          # Construct the date for the new version
          DATE=$(date '+%y.%m')
          
          # Separate new 
          YEAR=$(echo $DATE | cut -d'.' -f1)
          MONTH=$(echo $DATE | cut -d'.' -f2)
          
          ## --- Handling of special cases ---
          # Move to the previous year
          if [ "$MONTH" == "01" ]; then
          PREV_MONTH="12"
          YEAR=$(($YEAR - 1))
          # 09 and 08 will be interpreted in Octal, so they have to be handled differently 
          elif [ "$MONTH" == "09" ]; then
          PREV_MONTH="08"
          elif [ "$MONTH" == "08" ]; then
          PREV_MONTH="07"
          else
          PREV_MONTH=$(($MONTH - 1))
          # Ensure the previous month is 2 digits
          PREV_MONTH=$(printf "%02d" $PREV_MONTH)
          fi
          
          # Construct the new version
          NEW_VERSION="${YEAR}.${PREV_MONTH}"
          cd docker
          
          # OLD_VERSION=${{ steps.get_version.outputs.old_version }}
          # NEW_VERSION=${{ steps.get_version.outputs.new_version }}
          sed -i "s/$FILE_VERSION/$NEW_VERSION/g" Dockerfile.release

          # Show diff
          echo "Diff after update:"
          git diff docker/Dockerfile.release || true

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Check for changes
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git add docker/Dockerfile.release
          git commit -m "Update pytorch image in Dockerfile.release to version $NEW_VERSION"
          git push origin HEAD:${GITHUB_REF}